package com.azadi.carmechanicar
import android.app.Activity
import android.content.Intent
import android.graphics.*
import android.net.Uri
import android.os.Bundle
import android.provider.OpenableColumns
import android.widget.*
import com.azadi.carmechanicar.ai.OnDeviceCarPartClassifier
import com.azadi.carmechanicar.data.PartRepository
import com.azadi.carmechanicar.util.Ui
class GalleryAnalysisActivity:Activity(){private lateinit var image:ImageView;private lateinit var result:LinearLayout;private var classifier:OnDeviceCarPartClassifier?=null;override fun onCreate(b:Bundle?){super.onCreate(b);classifier=try{OnDeviceCarPartClassifier(this)}catch(_:Exception){null};val scroll=ScrollView(this);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(Ui.dp(context,16),Ui.dp(context,16),Ui.dp(context,16),Ui.dp(context,24));setBackgroundColor(Color.rgb(5,9,13))};scroll.addView(root);root.addView(Ui.title(this,"تحلیل واقعی تصویر",24f));root.addView(Ui.body(this,"قطعه را نزدیک مرکز تصویر قرار دهید؛ پردازش روی دستگاه انجام می‌شود.",14f,Color.LTGRAY));root.addView(Ui.primaryButton(this,"انتخاب تصویر"){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{addCategory(Intent.CATEGORY_OPENABLE);type="image/*"},901)});image=ImageView(this).apply{adjustViewBounds=true};root.addView(image);result=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};root.addView(result);root.addView(Ui.primaryButton(this,"بازگشت"){finish()});setContentView(scroll)};override fun onActivityResult(r:Int,c:Int,d:Intent?){super.onActivityResult(r,c,d);if(r==901&&c==RESULT_OK){val uri=d?.data?:return;image.setImageURI(uri);analyze(uri)}};private fun analyze(uri:Uri){result.removeAllViews();result.addView(Ui.body(this,"در حال تحلیل…",15f,Color.rgb(41,213,255)));val e=classifier?:return;Thread{try{val bm=ImageDecoder.decodeBitmap(ImageDecoder.createSource(contentResolver,uri)){dec,_,_->dec.allocator=ImageDecoder.ALLOCATOR_SOFTWARE};val x=e.classify(bm);bm.recycle();runOnUiThread{result.removeAllViews();if(x==null||x.confidence<OnDeviceCarPartClassifier.MIN_CONFIDENCE){result.addView(Ui.body(this,"قطعه پشتیبانی‌شده‌ای با اطمینان کافی تشخیص داده نشد.",14f,Color.YELLOW))}else{val p=PartRepository.byId(x.partId);if(p!=null){result.addView(Ui.title(this,"${p.nameFa} • ${(x.confidence*100).toInt()}٪",20f));result.addView(Ui.body(this,p.shortDescription));result.addView(Ui.primaryButton(this,"جزئیات"){startActivity(Intent(this,PartDetailActivity::class.java).putExtra("partId",p.id))})}}}}catch(ex:Exception){runOnUiThread{result.removeAllViews();result.addView(Ui.body(this,"خطا: ${ex.message}",14f,Color.RED))}}}.start()};override fun onDestroy(){classifier?.close();super.onDestroy()}}
